### PR TITLE
Features/update navbar styling

### PR DESCRIPTION
**Pull request by anilnatha**
## Purpose
- Updated css styling of desktop and mobile menu to match our Figma designs
## Proposed Changes
- [CHANGE] Updated Navbar CSS styling to match Figma Design
## Issues
- [unity-ui/issue-5](https://github.com/unity-sds/unity-ui/issues/5)
## Testing
- Local browser testing

### CODE REVIEW

**Comment by anilnatha** [comment]
See linked issue for screenshots of updated designs.

**Comment by rtapella** [comment]
Is this deployed somewhere?

**Comment by anilnatha** [comment]
@rtapella This is ready for review once again, see the linked ticket for additional info regarding the border fix I added.

image

**Review by rtapella — APPROVED** [review]
👍

**Pull request merged**
